# -*- coding: utf-8 -*-
"""Phishing.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aHEOaTvoHc6UTH9NAoRWqAbOu3wEkTsM

!pip install streamlit
!pip install validators
!npm install -g localtunnel
!apt-get install -y cloudflared

from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/Deploy_TA/deteksi_phishing.py'"
"""

import sys
import joblib

file_path = "D:/Skripsi_120140222/Deploy/deteksi_phishing.py"
model_path = "D:/Skripsi_120140222/Deploy/DOFA-XGBoost_model.pkl"
sys.path.append("D:/Skripsi_120140222/Deploy")

model_2 = joblib.load(model_path)

import streamlit as st
from deteksi_phishing import extract_features, predict_from_url

"""%%writefile app.py
"""
def main():
    # Judul aplikasi
    st.title("Deteksi Phishing Berbasis URL")

    # Input URL dari pengguna
    url = st.text_input("Masukkan URL yang ingin Anda deteksi:")

    if url:
        # Menampilkan URL yang dimasukkan
        st.write(f"URL yang dimasukkan: {url}")

        # Melakukan prediksi menggunakan URL baru dan model
        prediction_result, processed_url = predict_from_url(url, model_2)

        # Menampilkan hasil prediksi
        st.write(prediction_result)

        # Menambahkan tombol untuk prediksi ulang
        if st.button('Masukkan URL Lain'):
            st.experimental_rerun()  # Untuk mereload aplikasi dan memasukkan URL baru
if __name__ == "__main__":
    main()

